runtime: go111

#[START env_variables]
env_variables:
  PORT: 8080
  GO_ENV: "production"
#[END env_variables]

handlers:
- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt
- url: /assets
  static_dir: public/assets
- url: /.*
  script: auto
