---
development:
  dialect: postgres
  database: recommmended_development
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

production:
  dialect: postgres
  database: recommmended_production
  user: {{env "DATABASE_USER"}}
  password: {{env "DATABASE_PASSWORD"}}
  host: {{env "DATABASE_HOST"}}
  url: {{env "DATABASE_URL"}}
  pool: 1
  idle_pool: 1

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/recommmended_test?sslmode=disable"}}