package actions

import (

  "fmt"
  "github.com/gobuffalo/buffalo"
  "github.com/gobuffalo/pop"
  "recommmended/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Artist)
// DB Table: Plural (artists)
// Resource: Plural (Artists)
// Path: Plural (/artists)
// View Template Folder: Plural (/templates/artists/)

// ArtistsResource is the resource for the Artist model
type ArtistsResource struct{
  buffalo.Resource
}

// List gets all Artists. This function is mapped to the path
// GET /artists
func (v ArtistsResource) List(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  artists := &models.Artists{}

  // Paginate results. Params "page" and "per_page" control pagination.
  // Default values are "page=1" and "per_page=20".
  q := tx.PaginateFromParams(c.Params())

  // Retrieve all Artists from the DB
  if err := q.All(artists); err != nil {
    return err
  }

  // Add the paginator to the context so it can be used in the template.
  c.Set("pagination", q.Paginator)

  return c.Render(200, r.Auto(c, artists))
}

// Show gets the data for one Artist. This function is mapped to
// the path GET /artists/{artist_id}
func (v ArtistsResource) Show(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Artist
  artist := &models.Artist{}

  // To find the Artist the parameter artist_id is used.
  if err := tx.Find(artist, c.Param("artist_id")); err != nil {
    return c.Error(404, err)
  }

  return c.Render(200, r.Auto(c, artist))
}

// New renders the form for creating a new Artist.
// This function is mapped to the path GET /artists/new
func (v ArtistsResource) New(c buffalo.Context) error {
  return c.Render(200, r.Auto(c, &models.Artist{}))
}
// Create adds a Artist to the DB. This function is mapped to the
// path POST /artists
func (v ArtistsResource) Create(c buffalo.Context) error {
  // Allocate an empty Artist
  artist := &models.Artist{}

  // Bind artist to the html form elements
  if err := c.Bind(artist); err != nil {
    return err
  }

  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Validate the data from the html form
  verrs, err := tx.ValidateAndCreate(artist)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    // Make the errors available inside the html template
    c.Set("errors", verrs)

    // Render again the new.html template that the user can
    // correct the input.
    return c.Render(422, r.Auto(c, artist))
  }

  // If there are no errors set a success message
  c.Flash().Add("success", T.Translate(c, "artist.created.success"))
  // and redirect to the artists index page
  return c.Render(201, r.Auto(c, artist))
}

// Edit renders a edit form for a Artist. This function is
// mapped to the path GET /artists/{artist_id}/edit
func (v ArtistsResource) Edit(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Artist
  artist := &models.Artist{}

  if err := tx.Find(artist, c.Param("artist_id")); err != nil {
    return c.Error(404, err)
  }

  return c.Render(200, r.Auto(c, artist))
}
// Update changes a Artist in the DB. This function is mapped to
// the path PUT /artists/{artist_id}
func (v ArtistsResource) Update(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Artist
  artist := &models.Artist{}

  if err := tx.Find(artist, c.Param("artist_id")); err != nil {
    return c.Error(404, err)
  }

  // Bind Artist to the html form elements
  if err := c.Bind(artist); err != nil {
    return err
  }

  verrs, err := tx.ValidateAndUpdate(artist)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    // Make the errors available inside the html template
    c.Set("errors", verrs)

    // Render again the edit.html template that the user can
    // correct the input.
    return c.Render(422, r.Auto(c, artist))
  }

  // If there are no errors set a success message
  c.Flash().Add("success", T.Translate(c, "artist.updated.success"))
  // and redirect to the artists index page
  return c.Render(200, r.Auto(c, artist))
}

// Destroy deletes a Artist from the DB. This function is mapped
// to the path DELETE /artists/{artist_id}
func (v ArtistsResource) Destroy(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Artist
  artist := &models.Artist{}

  // To find the Artist the parameter artist_id is used.
  if err := tx.Find(artist, c.Param("artist_id")); err != nil {
    return c.Error(404, err)
  }

  if err := tx.Destroy(artist); err != nil {
    return err
  }

  // If there are no errors set a flash message
  c.Flash().Add("success", T.Translate(c, "artist.destroyed.success"))
  // Redirect to the artists index page
  return c.Render(200, r.Auto(c, artist))
}
